version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: ai_rate_limiter_postgres
    environment:
      POSTGRES_DB: ai_rate_limiter
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ai_rate_limiter_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis
  redis:
    image: redis:7-alpine
    container_name: ai_rate_limiter_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ai_rate_limiter_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # RabbitMQ
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: ai_rate_limiter_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-guest}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - ai_rate_limiter_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # APISIX Gateway (Standalone Mode)
  apisix:
    image: apache/apisix:3.7.0-debian
    container_name: ai_rate_limiter_apisix
    ports:
      - "9080:9080"
      - "9180:9180"
    environment:
      APISIX_STAND_ALONE: "true"
    volumes:
      - ./apisix_config/config.yaml:/usr/local/apisix/conf/config.yaml:ro
      - ./apisix_config/routes.yaml:/usr/local/apisix/conf/routes.yaml:ro
    networks:
      - ai_rate_limiter_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9180/apisix/admin/plugins"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Flask Application
  flask_app:
    build: .
    container_name: ai_rate_limiter_app
    ports:
      - "8501:8501"
    env_file:
      - .env
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
    volumes:
      - ./logs:/app/logs
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - ai_rate_limiter_network
    restart: unless-stopped

  # Celery Worker
  celery_worker:
    build: .
    container_name: ai_rate_limiter_worker
    command: celery -A app.celery worker --loglevel=info --concurrency=4
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - ai_rate_limiter_network
    restart: unless-stopped

  # Celery Beat (Scheduler)
  celery_beat:
    build: .
    container_name: ai_rate_limiter_beat
    command: celery -A app.celery beat --loglevel=info --scheduler celery.beat.PersistentScheduler --schedule=/tmp/celerybeat-schedule
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - .:/app
      - celery_beat_data:/tmp
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - ai_rate_limiter_network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:
  celery_beat_data:
  apisix_temp:

networks:
  ai_rate_limiter_network:
    driver: bridge 