apisix:
  node_listen: 9080
  enable_admin: true
  admin_listen:
    port: 9180
  allow_admin:
    - 0.0.0.0/0
  admin_key:
    - key: edd1c9f034335f136f87ad84b625c8f1
      role: admin

# Standalone mode configuration
standalone: true 