routes:
  # Test route
  - uri: /test
    name: test_route
    desc: Test route for APISIX
    methods:
      - GET
    plugins:
      http_proxy:
        host: httpbin.org
        port: 443
        scheme: https
        timeout:
          connect: 60
          send: 60
          read: 60

  # OpenAI API Route
  - uri: /v1/chat/completions/openai
    name: openai_chat_completions
    desc: OpenAI Chat Completions API with rate limiting
    methods:
      - POST
    plugins:
      limit-req:
        rate: 10
        burst: 20
        nodelay: false
        rejected_code: 429
        key_type: var
        key: remote_addr
      proxy-rewrite:
        regex_uri: ["^/v1/chat/completions/openai", "/v1/chat/completions"]
      http_proxy:
        host: api.openai.com
        port: 443
        scheme: https
        timeout:
          connect: 60
          send: 60
          read: 60
      cors:
        allow_origins: "*"
        allow_methods: "GET,POST,PUT,DELETE,OPTIONS"
        allow_headers: "*"
        expose_headers: "*"
        max_age: 3600
        allow_credential: true 